### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' Using openflow-api

### ISSUE THREAD

**Issue by DmaxDude** [open-rpa/openflow-api#1]
Not able to serve my application if I use NgOpenflowAuthService 
getting error
Error: ./node_modules/@openiap/openflow-api/lib/node/file-system-cache/funcs.js
Module not found: Error: Can't resolve 'crypto' in 'E:\synergerp_work\SynergAutomate\node_modules\@openiap\openflow-api\lib\node\file-system-cache'

Error: ./node_modules/@openiap/openflow-api/lib/node/file-system-cache/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\synergerp_work\SynergAutomate\node_modules\@openiap\openflow-api\lib\node\file-system-cache'

Error: ./node_modules/@openiap/openflow-api/lib/node/file-system-cache/funcs.js
Module not found: Error: Can't resolve 'fs' in 'E:\synergerp_work\SynergAutomate\node_modules\@openiap\openflow-api\lib\node\file-system-cache'

Error: ./node_modules/@openiap/openflow-api/lib/node/WebSocketClient.js
Module not found: Error: Can't resolve 'path' in 'E:\synergerp_work\SynergAutomate\node_modules\@openiap\openflow-api\lib\node'

Error: ./node_modules/@openiap/openflow-api/lib/node/file-system-cache/index.js
Module not found: Error: Can't resolve 'path' in 'E:\synergerp_work\SynergAutomate\node_modules\@openiap\openflow-api\lib\node\file-system-cache'

Error: ./node_modules/@openiap/openflow-api/lib/node/file-system-cache/funcs.js
Module not found: Error: Can't resolve 'path' in 'E:\synergerp_work\SynergAutomate\node_modules\@openiap\openflow-api\lib\node\file-system-cache'

**Comment by skadefro** [comment]
this was fixed a while ago
